### ISSUE TITLE
Detail Instruction about installation Cloud-Portal

### ISSUE THREAD

**Issue by vmpowercli** [chrisipa/cloud-portal#65]
Hello, do you have a document about details instructions for installing Cloud-Portal? I would really appreciate if you can provide one.

Thank You

**Comment by chrisipa** [comment]
Please have a look at the prerequisites section of the README.md file:

https://github.com/chrisipa/cloud-portal#prerequisites

Installation is basically pretty easy. You can either use the Ansible installer or start from scratch:

https://github.com/chrisipa/cloud-portal/blob/master/docs/installation/README.md

In case you are starting from scratch you have to install docker & docker-compose on your Linux machine and follow these instructions:

https://github.com/chrisipa/cloud-portal/blob/master/modules/cloud-portal-server/README.md#Usage

Are you still missing some details in the documentation? Please let me know.

**Comment by chrisipa** [comment]
Closed due to inactivity ...

**Comment by vmpowercli** [comment]
Sorry for the late reply.. Going to give another shot again.. I will let you know how it goes.. thanks again
