### ISSUE TITLE
Portal wont open

### ISSUE THREAD

**Issue by vmpowercli** [chrisipa/cloud-portal#66]
I installed the portal using the docker file and when I tried to hit the page i get HTTP STAUS 404 - NOT FOUND. Can you please help me here?

**Comment by vmpowercli** [comment]
chrisipa@561d5e883d86:/$ curl http://localhost:8080
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.8</h3></body></html>chrisipa@561d5e883d86:/$

**Comment by chrisipa** [comment]
Can you post the log file of the Spring boot application? It seems like there was a problem creating the Spring context. My guess is that the connection to the MongoDB is not working properly. It would also be helpful to get your Docker compose configuration file here (please remove any passwords, secrets, etc.).

**Comment by vmpowercli** [comment]
I just created a docker image from this configuration 
mongodb:
  image: mongo:3.4.10
  volumes:
    - /opt/cloud-portal/data:/data/db

tomcat:
  image: chrisipa/cloud-portal-server:latest
  links:
    - mongodb
  ports:
    - 80:8080
    - 443:8443
  volumes:
    - /opt/cloud-portal/logs:/opt/tomcat/logs
  environment:
    - 'APPLICATION_TITLE=My Cloud Portal'
    - 'APPLICATION_ADMIN_GROUP=my-admin-group'
    - 'ENCRYPTOR_SECRET=my-encryptor-secret'
    - 'LDAP_BASE_DN=dc=my,dc=domain'
    - 'LDAP_GROUP_ATTRIBUTE=memberOf'
    - 'LDAP_LOGIN_ATTRIBUTE=userPrincipalName'
    - 'LDAP_PASSWORD=my-ldap-password'
    - 'LDAP_PRINCIPAL=cn=my-admin-user,ou=users,dc=my,dc=domain'
    - 'LDAP_URL_STRING=ldap://my-ldap-server-1:389,ldap://my-ldap-server-2:389'
    - 'LDAP_USER_SEARCH_FILTER=(objectClass=inetOrgPerson)'
    - 'MAIL_FROM=no-reply@my-domain.com'
    - 'MAIL_CC=my-cc-account@my-domain.com'
    - 'MAIL_HOST=my-mail-server'
    - 'MAIL_SEND=true'
    - 'MONGO_DB_URI=mongodb://mongodb:27017/cloud-portal'

**Comment by chrisipa** [comment]
Can you post the output of the *cloud-portal.log*?

**Comment by chrisipa** [comment]
Can you please attach the *cloud-portal.log* file here?

**Comment by vmpowercli** [comment]
I looked up inside the Server and even inside the Docker Container and could not able to find the cloud-portal.log file. Can  you please help me find it .. like where to look...

**Comment by vmpowercli** [comment]
I found the location for Cloud-portal/logs but there are no logs inside the folder.

**Comment by chrisipa** [comment]
I think now I know what could be the problem. Please make sure to create a underprivileged user to run the cloud portal container. See this url as a reference:

https://github.com/chrisipa/docker-library/blob/master/debian-pom/java-pom/tomcat-pom/tomcat/README.md#preparation-create-a-underprivileged-user-on-the-host-system

**Comment by vmpowercli** [comment]
I followed the above doc and added right permissions.. but still it did not work...

**Comment by chrisipa** [comment]
Can you post the output of the following command here?

`docker logs tomcat`

**Comment by vmpowercli** [comment]
I gave up.. I tried all possible ways and it wont work.. Sorry :)
